[package]
name = "rs3-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Object-store abstraction for rs3"

[features]
default = []
s3 = [
  "dep:aws-config",
  "dep:aws-sdk-s3",
  "dep:metrics",
  "dep:object_store",
  "dep:rustls",
]

[dependencies]
async-trait.workspace = true
aws-config = { version = "1", default-features = false, features = [
  "behavior-version-latest",
  "default-https-client",
  "rt-tokio",
], optional = true }
aws-sdk-s3 = { version = "1", default-features = false, features = [
  "behavior-version-latest",
  "default-https-client",
  "http-1x",
  "rt-tokio",
  "sigv4a",
], optional = true }
bytes.workspace = true
metrics = { workspace = true, optional = true }
object_store = { workspace = true, optional = true }
rs3-types.workspace = true
rustls = { version = "0.23", default-features = false, features = [
  "aws_lc_rs",
], optional = true }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
