[package]
name = "rs3-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Object-store abstraction for rs3"

[features]
default = []
s3 = ["dep:aws-sdk-s3", "dep:metrics", "dep:object_store"]

[dependencies]
async-trait.workspace = true
aws-sdk-s3 = { version = "1", optional = true }
bytes.workspace = true
metrics = { workspace = true, optional = true }
object_store = { workspace = true, optional = true }
rs3-types.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
