{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rs3-gateway.fullname" . }}
  labels:
    {{- include "rs3-gateway.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rs3-gateway.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    -{{- with .Values.networkPolicy.egress.backend.to }}
      to:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ports:
        {{- toYaml .Values.networkPolicy.egress.backend.ports | nindent 8 }}
    -{{- with .Values.networkPolicy.egress.kubeApi.to }}
      to:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ports:
        {{- toYaml .Values.networkPolicy.egress.kubeApi.ports | nindent 8 }}
{{- end -}}
