{{- if and .Values.credentials.create (not .Values.credentials.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rs3-gateway.secretName" . }}
  labels:
    {{- include "rs3-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.credentials.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.credentials.secretAccessKey | b64enc | quote }}
{{- end -}}
{{- if and .Values.backendCredentials.create (not .Values.backendCredentials.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rs3-gateway.fullname" . }}-backend
  labels:
    {{- include "rs3-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.backendCredentials.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.backendCredentials.secretAccessKey | b64enc | quote }}
{{- end -}}
{{- if and .Values.repositoryKeys.create (not .Values.repositoryKeys.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rs3-gateway.repositoryKeySecretName" . }}
  labels:
    {{- include "rs3-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  envelope-object-id: {{ .Values.repositoryKeys.envelopeObjectId | b64enc | quote }}
  wrapping-key-id: {{ .Values.repositoryKeys.wrappingKeyId | b64enc | quote }}
  wrapping-key-hex: {{ .Values.repositoryKeys.wrappingKeyHex | b64enc | quote }}
  salt-hex: {{ .Values.repositoryKeys.saltHex | b64enc | quote }}
{{- end -}}
