{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rs3-gateway.fullname" . }}
  labels:
    {{- include "rs3-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rs3-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
{{- end -}}
