{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rs3-gateway.serviceAccountName" . }}
  labels:
    {{- include "rs3-gateway.labels" . | nindent 4 }}
{{- end -}}
