apiVersion: v1
kind: Service
metadata:
  name: {{ include "rs3-gateway.fullname" . }}
  labels:
    {{- include "rs3-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rs3-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.service.port }}
      targetPort: s3
