[package]
name = "rs3-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Command-line entry point for the rs3 gateway"

[dependencies]
anyhow.workspace = true
clap.workspace = true
rs3-types = { path = "../rs3-types" }
secrecy.workspace = true
s3s.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
